// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsNeedLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_LOGIN.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorNeedLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_NEED_LOGIN.String(), fmt.Sprintf(format, args...))
}

func IsDbFiled(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FILED.String() && e.Code == 500
}

func ErrorDbFiled(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FILED.String(), fmt.Sprintf(format, args...))
}

func IsOvderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OVDER_REVIEWED.String() && e.Code == 400
}

func ErrorOvderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_OVDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

func IsOvderReplyed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OVDER_REPLYED.String() && e.Code == 402
}

func ErrorOvderReplyed(format string, args ...interface{}) *errors.Error {
	return errors.New(402, ErrorReason_OVDER_REPLYED.String(), fmt.Sprintf(format, args...))
}
