syntax = "proto3";

package api.review.v1;

option go_package = "review-service/api/review/v1;v1";
option java_multiple_files = true;
option java_package = "api.review.v1";

import "google/api/annotations.proto";
import "validate/validate.proto";

// 定义评价服务
service Review {
	rpc CreateReview (CreateReviewRequest) returns (CreateReviewReply){
		option(google.api.http) = {
			post: "s/v1/review",
			body: "*"
		};
	};
	// ListReviewByStoreID商家ID查询
	rpc ListReviewByStoreID (ListReviewByStoreIDRequest) returns (ListReviewByStoreIDReply){};
}

// 创建评价的参数
message CreateReviewRequest {
	int64 userID = 1 [(validate.rules).int64 = {gt: 0}];
	int64 orderID = 2 [(validate.rules).int64 = {gt: 0}];
	int32 score = 3 [(validate.rules).int32 = {in: [1,2,3,4,5]}];
	int32 serviceScore = 4 [(validate.rules).int32 = {in: [1,2,3,4,5]}];
	int32 expressScore = 5 [(validate.rules).int32 = {in: [1,2,3,4,5]}];
	string content = 6 [(validate.rules).string = {min_len: 2, max_len: 200}];
	string picInfo = 7; //图片信息
	string videoInfo = 8;
	bool anonymous = 9; //是否匿名
}

// 创建评价的回复
message CreateReviewReply {
	int64 reviewID = 1;
}

message ListReviewByStoreIDRequest{
	int64 storeID = 1 [(validate.rules).int64 = {gt: 0}];
	int32 page = 2 [(validate.rules).int32 = {gt: 0}];
	int32 size = 3 [(validate.rules).int32 = {gt: 0}];
}

message ListReviewByStoreIDReply{
	repeated ReviewInfo list = 1;
}

message ReviewInfo{
	int64 reviewID = 1;
	int64 userID = 2;
	int64 orderID = 3;
	int64 score = 4;
	int64 serviceScore = 5;
	int64 expressScore = 6;
	string content = 7;
	string picInfo = 8;
	string videoInfo = 9;
}