// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-B/internal/biz"
	"review-B/internal/conf"
	"review-B/internal/data"
	"review-B/internal/server"
	"review-B/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscover(registry)
	reviewClient := data.NewReviewServiceClient(discovery)
	dataData, cleanup, err := data.NewData(reviewClient, logger)
	if err != nil {
		return nil, nil, err
	}
	businesserRepo := data.NewBusinesserRepo(dataData, logger)
	businesserUsecase := biz.NewBusinesserUsecase(businesserRepo, logger)
	businesserService := service.NewBusinesserService(businesserUsecase)
	grpcServer := server.NewGRPCServer(confServer, businesserService, logger)
	httpServer := server.NewHTTPServer(confServer, businesserService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
