// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-service/internal/biz"
	"review-service/internal/conf"
	"review-service/internal/data"
	"review-service/internal/server"
	"review-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	registrar := server.NewRegister(registry)
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	reviewerRepo := data.NewreviewRepo(dataData, logger)
	reviewerUsecase := biz.NewReviewerUsecase(reviewerRepo, logger)
	reviewService := service.NewReviewService(reviewerUsecase)
	businessRepo := data.NewbusinessRepo(dataData, logger)
	businessUsecase := biz.NewBusinessUsecase(businessRepo, logger)
	businessService := service.NewBusinessService(businessUsecase)
	grpcServer := server.NewGRPCServer(confServer, reviewService, businessService, logger)
	httpServer := server.NewHTTPServer(confServer, reviewService, businessService, logger)
	app := newApp(logger, registrar, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
